routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('links', 'LinkController')->only([ 'store', 'show', 'update' ]);

Route::get('{source}', 'LinkController@redirect')->name('links.redirect');

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [ 'source', 'destination', 'session_id' ];

    public static function generate($length) {
        $words = config('words');

        $link = collect();

        for($i = 0; $i < $length; $i++) {
            $link[] = \Arr::random($words);
        }

        return $link->join('-');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;
use Faker\Factory as FakerFactory;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!starts_with($request->get('destination'), 'http')) {
            $request->merge([ 'destination' => 'http://' . $request->get('destination') ]);
        }

        $validated = $this->validate($request, [
            'destination' => 'url|required'
        ]);

        $validated['session_id'] = session()->getId();
        $validated['source'] = null;

        $tries = 0;
        $length = 3;

        while($validated['source'] ===  null || Link::where('source', $validated['source'])->count() != 0) {

            if($tries > 0 && $tries % 1000 === 0) {
                $length = $length + 1;
            }

            $validated['source'] = Link::generate($length);
            \Log::info($validated['source']);

            $tries++;

        }

        $link = Link::create($validated);

        return redirect()->route('links.show', $link);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function show(Link $link)
    {
        if($link->session_id === session()->getId()) {
            return view('home', [ 'link' => $link ]);
        }

        return view('home')->withErrors([ 'This is not one of your links. You can not edit it!' ]);
    }

    public function redirect($source) {
        $link = Link::where('source', $source)->get()->last();

        return redirect($link->destination);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function edit(Link $link)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Link $link)
    {
        if($link->session_id != session()->getId()) {
            return redirect()->back()->withErrors([ 'This link is not yours. You can not change it.' ]);
        }

        $this->validate($request, [
            'source' => 'required|alpha_dash|unique:links'
        ]);

        $link->source = $request->input('source');
        $link->update();

        return redirect()->back()->with('success', 'Updated link.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function destroy(Link $link)
    {
        //
    }
}

resources/views/home.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link href="/css/iconfont.css" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="/css/main.css">

        <script src="/js/app.js"></script>

        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    </head>
    <body>
        <div class="flex flex-col items-center justify-center min-h-full py-16">
            <a href="/" class="flex flex-col items-end">
                <div class="text-5xl">
                    remember
                </div>
                <div class="text-xl">
                    .link
                </div>
            </a>
            @if (count($errors->all()))
                <div class="mt-16 md:rounded-lg bg-red-100 text-red-600 p-8 self-stretch">
                    <div class="font-bold mb-4">
                        There were some errors!
                    </div>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if (session('success'))
                <div class="mt-16 md:rounded-lg bg-green-100 text-green-600 p-8 self-stretch">
                    <div class="font-bold mb-4">
                        Success!
                    </div>
                    {{ session('success') }}
                </div>
            @endif
            <form method="POST" action="{{ route('links.store') }}" class="mt-16 flex flex-row items-center justify-center">
                {{ csrf_field() }}
                <input type="text" name="destination" placeholder="Type in your link..." value="{{ old('destination') }}" class="p-4 border rounded-l-lg
                @if($errors->has('destination'))
                    border-red-500
                @endif
                ">
                <button type="submit" class="rounded-r-lg border-green-500 font-bold text-green-500 p-4 border transition hover:text-white hover:bg-green-500">Convert</button>
            </form>

            @if (isset($link))
                <div class="rounded-lg md:border-green-200 md:border-2 p-8 mt-16 container">
                    <div class="font-bold mb-4 text-green-500">
                        Here is your link!
                    </div>

                    <form action="{{ route('links.update', $link) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <pre class="bg-gray-200 md:rounded-lg py-4 px-8 my-4 -mx-8 md:mx-0"><code class="table w-full"><label class="table-cell">{{ route('links.redirect', ['source' => '']) }}/</label><div class="w-full table-row md:table-cell"><input id="link-input" class="bg-transparent w-full" type="text" name="source" value="{{ old('source') ?? $link->source }}"></div></code></pre>
                        <div class="flex flex-row justify-end items-center cursor-pointer select-none copy-link font-bold text-gray-500" data-clipboard-text="{{ route('links.redirect', [ 'source' => $link->source ]) }}">
                            <i class="feather icon-clipboard mr-2"></i>
                            Copy to clipboard
                        </div>
                        <div class="mt-4">
                            You can now edit your link so that it is better memorizable.
                        </div>
                        <button type="submit" class="mt-4 rounded-lg border-green-500 font-bold text-green-500 p-4 border transition hover:text-white hover:bg-green-500">Save changes</button>
                    </form>
                </div>
            @endif
        </div>
    </body>
</html>